(()=>{'use strict';
const $=s=>document.querySelector(s), STORE='pv-local-profile-v1';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const read=(key)=>{try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return {}}};
const themes=[['light','☀','Светлая','Мягкий светлый фон'],['dark','☾','Тёмная','Спокойный ночной режим'],['system','◐','Системная','Как на устройстве']];
let dialog,previousFocus;
function updateProfileMenu(){const p=read(STORE);document.querySelectorAll('[data-open-login]').forEach(btn=>{btn.innerHTML=p.nickname?'<span>♙</span> <span class="pv-user-name"></span> <span class="menu-chevron">↗</span>':'<span>♙</span> Создать профиль <span class="menu-chevron">↗</span>';if(p.nickname)btn.querySelector('.pv-user-name').textContent=p.nickname;btn.title=p.nickname?'Открыть профиль '+p.nickname:'Создать локальный профиль'})}

function ensureDialog(){if(dialog)return;dialog=document.createElement('div');dialog.className='pv-leader-overlay';dialog.hidden=true;dialog.innerHTML='<section class="pv-leader-dialog" role="dialog" aria-modal="true" aria-labelledby="pv-leader-title"><header class="pv-leader-head"><div><span class="pv-leader-kicker">МОЁ ОБУЧЕНИЕ</span><h2 id="pv-leader-title">Профиль и рейтинг</h2></div><button class="pv-close" type="button" aria-label="Закрыть">✕</button></header><div id="pv-leader-body"></div></section>';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog||e.target.closest('.pv-close'))hide()});dialog.addEventListener('submit',submit);dialog.addEventListener('click',e=>{if(e.target.closest('#pv-translate'))translate();if(e.target.closest('#pv-delete-account'))deleteProfile()})}
function hide(){dialog.hidden=true;previousFocus?.focus?.()}
function stats(){const d=read('pv-learning-v1'),events=Array.isArray(d.events)?d.events:[],mastery=Object.values(d.mastery||{});return{answers:events.length,lessons:mastery.filter(v=>v.complete).length,accuracy:events.length?Math.round(events.filter(v=>v.correct).length/events.length*100)+'%':'—'}}
const dictionary={ученик:'Uczeń',ученица:'Uczennica',кот:'Kot',кошка:'Kotka',друг:'Przyjaciel',подруга:'Przyjaciółka',мечтатель:'Marzyciel',путешественник:'Podróżnik',победитель:'Zwycięzca',солнце:'Słońce',польский:'Polski'};
function validate(name){const v=name.normalize('NFKC').trim(),plain=v.toLowerCase().replace(/[013457@]/g,c=>({'0':'o','1':'i','3':'e','4':'a','5':'s','7':'t','@':'a'}[c])).replace(/[^\p{L}]/gu,'');if(v.length<3||v.length>24)return'Ник должен содержать 3–24 символа';if(!/^[\p{L}\p{N}_ -]+$/u.test(v))return'Разрешены буквы, цифры, пробел, дефис и подчёркивание';if(['fuck','shit','cunt','nigger','nigga','сука','бляд','пизд','хуй','хуе','ебан','пидор','пидар','hitler'].some(word=>plain.includes(word)))return'Этот ник не подходит';return''}
function render(){const profile=read(STORE),s=stats();$('#pv-leader-body').innerHTML='<p class="pv-leader-copy">Никакой обязательной регистрации. Никнейм и прогресс хранятся только в этом браузере.</p><div class="pv-leader-stats"><div><span>Ответов</span><strong>'+s.answers+'</strong></div><div><span>Уроков</span><strong>'+s.lessons+'</strong></div><div><span>Точность</span><strong>'+s.accuracy+'</strong></div></div><form id="pv-profile-form"><label for="pv-nickname">Твой никнейм</label><div class="pv-nick-field"><input id="pv-nickname" maxlength="24" autocomplete="off" placeholder="Например, PolskiUczen" value="'+escape(profile.nickname||'')+'"><button type="button" id="pv-translate" class="pv-secondary">Перевести на польский</button></div><p id="pv-nick-feedback" role="status"></p><button class="pv-save" type="submit">Сохранить профиль</button><button class="pv-delete-profile" type="button" id="pv-delete-account" '+(profile.id?'':'hidden')+'>Удалить профиль</button></form><div class="pv-leader-info"><strong>Общий рейтинг пока не подключён</strong><p>Чтобы показывать достижения всех посетителей, нужен общий защищённый приём результатов. GitHub Pages без серверной части не может безопасно собирать и проверять результаты других пользователей. Здесь отображаются только твои данные.</p></div>'}
function deleteProfile(){if(!confirm('Удалить локальный профиль и ник с этого устройства? Учебный прогресс и планы останутся.'))return;try{localStorage.removeItem(STORE)}catch{}updateProfileMenu();render();const note=$('#pv-nick-feedback');if(note)note.textContent='Локальный профиль удалён. Учебный прогресс сохранён.'}
function submit(e){if(e.target.id!=='pv-profile-form')return;e.preventDefault();const input=$('#pv-nickname'),error=validate(input.value),msg=$('#pv-nick-feedback');if(error){msg.textContent=error;return}const profile=read(STORE);profile.nickname=input.value.normalize('NFKC').trim();if(!profile.id)profile.id=crypto.randomUUID?.()||'profile-'+Date.now()+'-'+Math.random().toString(36).slice(2);try{localStorage.setItem(STORE,JSON.stringify(profile));updateProfileMenu();render();const note=$('#pv-nick-feedback');if(note)note.textContent='✓ Профиль сохранён на этом устройстве';}catch{msg.textContent='Не удалось сохранить профиль'} }
function translate(){const field=$('#pv-nickname'),words=field.value.toLowerCase().trim().split(/\s+/),msg=$('#pv-nick-feedback');if(words.every(w=>dictionary[w])){field.value=words.map(w=>dictionary[w]).join(' ');msg.textContent='Проверь польский вариант и сохрани профиль'}else msg.textContent='Автоматический перевод доступен для небольшого словаря обычных слов; произвольные имена лучше выбрать вручную'}
function openProfile(){ensureDialog();previousFocus=document.activeElement;const old=document.querySelector('.global-overlay');if(old)old.hidden=true;render();dialog.hidden=false;dialog.querySelector('.pv-close')?.focus()}
document.addEventListener('click',e=>{const link=e.target.closest('a[href$="leaderboard.html"],[data-open-login]');if(link){e.preventDefault();e.stopImmediatePropagation();openProfile()}},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&dialog&&!dialog.hidden)hide()});
updateProfileMenu();window.addEventListener('storage',e=>{if(e.key===STORE)updateProfileMenu()});
function decorateSettings(){const modal=$('#global-modal-body');if(!modal||!$('#global-theme')||modal.dataset.upgraded)return;modal.dataset.upgraded='1';const select=$('#global-theme');select.classList.add('pv-original-select');const box=document.createElement('div');box.className='pv-theme-grid';box.setAttribute('role','group');box.setAttribute('aria-label','Тема оформления');box.innerHTML=themes.map(([v,icon,name,description])=>'<button type="button" class="pv-theme-option" data-theme-choice="'+v+'"><span class="pv-theme-icon">'+icon+'</span><strong>'+name+'</strong><small>'+description+'</small></button>').join('');select.insertAdjacentElement('afterend',box);function selected(){box.querySelectorAll('[data-theme-choice]').forEach(b=>{let active=b.dataset.themeChoice===select.value;b.classList.toggle('selected',active);b.setAttribute('aria-pressed',String(active))})}box.addEventListener('click',e=>{const b=e.target.closest('[data-theme-choice]');if(!b)return;select.value=b.dataset.themeChoice;select.dispatchEvent(new Event('change',{bubbles:true}));selected()});selected();modal.querySelectorAll('.global-toggle').forEach(el=>{el.classList.add('pv-toggle-card');const input=el.querySelector('input');if(!input)return;input.setAttribute('role','switch');input.setAttribute('aria-checked',String(input.checked));input.addEventListener('change',()=>input.setAttribute('aria-checked',String(input.checked)))})}
const observer=new MutationObserver(()=>{if($('#global-theme'))decorateSettings()});observer.observe(document.body,{childList:true,subtree:true});decorateSettings();
})();