(()=>{'use strict';
const $=s=>document.querySelector(s),KEY='pv-learning-v1',SET='pv-site-settings';
const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}};
const settings=()=>{try{return JSON.parse(localStorage.getItem(SET)||'{}')}catch{return {}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const speak=(text)=>{if(settings().voice===false||!('speechSynthesis' in window))return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='pl-PL';u.rate=Number(settings().speechRate)||.85;window.speechSynthesis.speak(u)};
window.pvSpeak=speak;
let ctx;function tone(type){if(settings().sounds===false)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;ctx??=new C();if(ctx.state==='suspended')ctx.resume();let pattern=type==='win'?[523,659,784]:type==='lose'?[330,294]:type==='correct'?[523,659]:[350,310];let t=ctx.currentTime+.02;pattern.forEach((freq,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.value=freq;o.connect(g);g.connect(ctx.destination);let at=t+i*.13;g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.045,at+.025);g.gain.exponentialRampToValueAtTime(.0001,at+.22);o.start(at);o.stop(at+.23)})}catch{}}
let previous='';const exercise=$('#exercise');if(exercise){const obs=new MutationObserver(()=>{const feedback=exercise.querySelector('.feedback');if(feedback){const key=feedback.textContent+'|'+exercise.querySelector('.lab-pill')?.textContent;if(key!==previous){previous=key;tone(feedback.classList.contains('right')?'correct':'wrong')}}else if(exercise.querySelector('h3')?.textContent.includes('Урок пройден!')){if(previous!=='win'){previous='win';tone('win')}}else if(exercise.querySelector('h3')?.textContent.includes('Попробуй ещё раз')){if(previous!=='lose'){previous='lose';tone('lose')}}});obs.observe(exercise,{childList:true,subtree:true})}
function buttons(){document.querySelectorAll('.phrase').forEach(el=>{if(el.querySelector('.listen-inline'))return;const pl=el.querySelector('strong[lang=pl]');if(!pl)return;const b=document.createElement('button');b.type='button';b.className='listen-inline';b.textContent='🔊';b.title='Прослушать польскую фразу';b.setAttribute('aria-label','Прослушать фразу');b.addEventListener('click',()=>speak(pl.textContent));pl.insertAdjacentElement('afterend',b)});document.querySelectorAll('.reader-content p').forEach(el=>{if(el.querySelector('.listen-inline')||el.textContent.length>350||!el.textContent.trim())return;const b=document.createElement('button');b.type='button';b.className='listen-inline';b.textContent='🔊';b.title='Прослушать абзац';b.setAttribute('aria-label','Прослушать абзац');b.addEventListener('click',()=>speak(el.textContent.replace('🔊','').trim()));el.append(b)});if(exercise&&!exercise.querySelector('.listen-exercise')){const h=exercise.querySelector('h3');if(h&&exercise.querySelector('.lab-pill')){const b=document.createElement('button');b.className='listen-inline listen-exercise';b.type='button';b.textContent='🔊 Озвучить фразу';b.addEventListener('click',()=>{const id=$('#video-select')?.value;const s=exercise.querySelector('.speech-example')?.textContent||h.textContent.match(/«([^»]+)»/)?.[1]||'';if(s)speak(s)});h.insertAdjacentElement('afterend',b)}}}
let pending=false;const observer=new MutationObserver(()=>{if(!pending){pending=true;queueMicrotask(()=>{pending=false;buttons()})}});observer.observe(document.body,{childList:true,subtree:true});buttons();
function summary(){const data=get(),plans=Array.isArray(data.savedPlans)?data.savedPlans:[];const done=Object.values(data.mastery||{}).filter(v=>v.complete).length;return {plans,done}}
function render(){const {plans,done}=summary();for(const sel of ['#saved-plans','#analytics-plans']){const el=$(sel);if(!el)continue;el.innerHTML=plans.length?plans.slice().reverse().map(p=>'<article class="saved-plan"><div><strong>'+esc(p.title||'Мой учебный план')+'</strong><p>'+Number(p.minutes)+' мин/день · '+Number(p.lessons)+' уроков/неделю · пройдено '+done+' уроков</p><small>Создан '+new Date(p.createdAt).toLocaleDateString('ru-RU')+'</small></div>'+(sel==='#saved-plans'?'<button type="button" class="lab-secondary" data-remove-plan="'+esc(p.id)+'">Удалить</button>':'')+'</article>').join(''):'<p class="lab-muted">Сохранённых планов пока нет. Создай первый в разделе «Учебный план».</p>'}}
document.addEventListener('click',e=>{if(e.target.closest('#save-goals')){const data=get();const title=$('#goal-title')?.value.trim()||'Мой учебный план',minutes=Math.max(5,Math.min(480,Number($('#goal-minutes')?.value)||20)),lessons=Math.max(1,Math.min(50,Number($('#goal-lessons')?.value)||3));data.savedPlans=Array.isArray(data.savedPlans)?data.savedPlans:[];data.savedPlans.push({id:'plan-'+Date.now(),title,minutes,lessons,createdAt:Date.now()});try{localStorage.setItem(KEY,JSON.stringify(data))}catch{}setTimeout(render,30);const hint=$('#plan-save-hint');if(hint)hint.textContent='✓ Сохранено как отдельный учебный план';tone('win');if(settings().notifications){const notify=document.createElement('div');notify.className='pv-toast';notify.textContent='✓ План «'+title+'» добавлен';document.body.append(notify);setTimeout(()=>notify.remove(),3600)}}const del=e.target.closest('[data-remove-plan]');if(del){const data=get();data.savedPlans=(data.savedPlans||[]).filter(p=>p.id!==del.dataset.removePlan);localStorage.setItem(KEY,JSON.stringify(data));render()}});
window.addEventListener('hashchange',render);setInterval(()=>{if(!document.hidden)render()},15000);render();
})();