(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const key='pv-learning-v1', defaultData=()=>({pairs:{},mastery:{},events:[],goals:{minutes:20,lessons:3,title:'Уверенно говорить по-польски'},tasks:[]});
let data;try{data=Object.assign(defaultData(),JSON.parse(localStorage.getItem(key)||'{}'))}catch{data=defaultData()}
if(!data.pairs||typeof data.pairs!=='object')data.pairs={};if(!data.mastery||typeof data.mastery!=='object')data.mastery={};if(!Array.isArray(data.events))data.events=[];if(!Array.isArray(data.tasks))data.tasks=[];
const save=()=>{try{localStorage.setItem(key,JSON.stringify(data))}catch(e){alert('Не удалось сохранить данные в браузере: '+e.message)}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
const idsafe=s=>/^[\w-]{11}$/.test(s), normalize=s=>String(s).trim().toLocaleLowerCase('pl-PL').replace(/[.,!?;:„”"«»]/g,'').replace(/\s+/g,' ');
const day=stamp=>{const d=new Date(stamp);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')};
const STARTER_ID='starter';const STARTER=[{"pl":"Dzień dobry","ru":"Добрый день","source":"editorial-starter"},{"pl":"Dobry wieczór","ru":"Добрый вечер","source":"editorial-starter"},{"pl":"Do widzenia","ru":"До свидания","source":"editorial-starter"},{"pl":"Cześć","ru":"Привет","source":"editorial-starter"},{"pl":"Dziękuję","ru":"Спасибо","source":"editorial-starter"},{"pl":"Proszę","ru":"Пожалуйста","source":"editorial-starter"},{"pl":"Przepraszam","ru":"Извините","source":"editorial-starter"},{"pl":"Jak się masz?","ru":"Как дела?","source":"editorial-starter"},{"pl":"Mam na imię Anna","ru":"Меня зовут Анна","source":"editorial-starter"},{"pl":"Nie rozumiem","ru":"Я не понимаю","source":"editorial-starter"},{"pl":"Gdzie jest dworzec?","ru":"Где находится вокзал?","source":"editorial-starter"},{"pl":"Ile to kosztuje?","ru":"Сколько это стоит?","source":"editorial-starter"},{"pl":"Mówię trochę po polsku","ru":"Я немного говорю по-польски","source":"editorial-starter"},{"pl":"Czy możesz powtórzyć?","ru":"Можешь повторить?","source":"editorial-starter"},{"pl":"Potrzebuję pomocy","ru":"Мне нужна помощь","source":"editorial-starter"}];
let mode=localStorage.getItem('pv-input-mode')||'tiles';if(!['tiles','mixed','typing'].includes(mode))mode='tiles';let assembly=[],bank=[],dragId=null;let autoPhrases={},videos=[],selected='',q=[],index=0,correct=0,answered=false,active=false;
function currentPairs(){if(selected===STARTER_ID)return STARTER;const manual=(data.pairs[selected]||[]).filter(x=>x&&x.pl&&x.ru);const auto=(autoPhrases[selected]?.phrases||[]).filter(x=>x&&x.pl).map(x=>({...x,auto:true}));const seen=new Set(manual.map(x=>normalize(x.pl)));return [...manual,...auto.filter(x=>!seen.has(normalize(x.pl)))].slice(0,40)}
function setTab(id){$$('.lab-tab').forEach(t=>t.hidden=t.id!==id);$$('[data-tab]').forEach(b=>b.classList.toggle('selected',b.dataset.tab===id));const names={practice:['Учи. Повторяй. Запоминай.','Два безошибочных раунда подтвердят освоение материала.'],texts:['Тексты для заучивания','Точные польские фразы с проверенным переводом, связанные с видеоуроками.'],analytics:['Твой прогресс в цифрах','Активность и подтверждённые знания — без выдуманной статистики.'],plan:['Учёба под твой ритм','Настраивай цели, отмечай выполненные задачи и отслеживай успехи.']};$('#tab-title').textContent=names[id][0];$('#tab-description').textContent=names[id][1];if(id==='texts')renderTexts();if(id==='analytics')renderAnalytics();if(id==='plan')renderPlan();history.replaceState(null,'','#'+id)}
$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>setTab(b.dataset.tab)));
function populate(){const search=$('#video-search').value.toLowerCase().trim();const matched=videos.filter(x=>x.title.toLowerCase().includes(search));const html=matched.map(v=>'<option value="'+esc(v.id)+'">'+esc(v.title.slice(0,115))+'</option>').join('');['video-select','text-video'].forEach(id=>{$('#'+id).innerHTML=html||'<option value="">Нет видео</option>';if(matched.some(x=>x.id===selected))$('#'+id).value=selected});if(!matched.some(x=>x.id===selected))selected=matched[0]?.id||'';$('#video-select').value=selected;$('#text-video').value=selected;renderSource();renderExerciseStatus();renderTexts()}
function selectVideo(id){selected=(id===STARTER_ID||idsafe(id))?id:'';active=false;q=[];index=0;correct=0;populate()}
$('#video-search').addEventListener('input',populate);$('#video-select').addEventListener('change',e=>selectVideo(e.target.value));$('#text-video').addEventListener('change',e=>selectVideo(e.target.value));
function renderSource(){const v=videos.find(x=>x.id===selected);if(selected===STARTER_ID){$('#video-details').innerHTML='<strong>Стартовый набор: 15 польских фраз</strong>Работает сразу, без YouTube API и субтитров. Это отдельно составленные базовые выражения, <b>не текст конкретного видеоролика</b>.';return}$('#video-details').innerHTML=v?'<strong>'+esc(v.title)+'</strong><a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/watch?v='+encodeURIComponent(v.id)+'">Сверить текст с оригинальным видео ↗</a><br>Сохранённых учебных фраз: '+currentPairs().length+' · Источник текста: вручную проверенный материал':'Каталог пока недоступен. Проверь синхронизацию YouTube.'}
function renderTexts(){if(!selected){$('#phrases').innerHTML='<p class="lab-muted">Нет выбранного видео.</p>';return}let p=currentPairs();$('#phrases').innerHTML=p.length?p.map((x,i)=>'<article class="phrase"><div><strong lang="pl">'+esc(x.pl)+'</strong><p>'+esc(x.ru||'Текст из польских субтитров — без перевода')+'</p><small>'+(x.auto?'Автоматически из субтитров YouTube':'Добавлено вручную · '+esc(x.added||''))+'</small></div>'+(x.auto||selected===STARTER_ID?'':'<button data-delete="'+(data.pairs[selected]||[]).indexOf(x)+'" aria-label="Удалить фразу">Удалить</button>')+'</article>').join(''):'<p class="lab-muted">Для этого урока фраз пока нет. Открой видео, проверь текст и добавь несколько предложений с переводом. После этого станут доступны тренажёры.</p>';renderSource()}
$('#add-pair').addEventListener('click',()=>{if(selected===STARTER_ID)return alert('Стартовый набор готов. Чтобы добавить свои фразы, выбери видео.');if(!selected)return alert('Выбери видео');$('#pair-dialog').hidden=false;$('#pair-pl').focus()});
function closeDialog(){$('#pair-dialog').hidden=true;$('#pair-form').reset()}$('#dialog-close').addEventListener('click',closeDialog);$('#dialog-overlay').addEventListener('click',closeDialog);
$('#pair-form').addEventListener('submit',e=>{e.preventDefault();if(!selected)return;const pl=$('#pair-pl').value.trim(),ru=$('#pair-ru').value.trim();if(!pl||!ru)return;data.pairs[selected]??=[];if(data.pairs[selected].some(p=>normalize(p.pl)===normalize(pl)))return alert('Такая фраза уже есть');data.pairs[selected].push({pl,ru,added:day(Date.now())});delete data.mastery[selected];save();closeDialog();renderTexts();renderExerciseStatus()});
$('#phrases').addEventListener('click',e=>{const b=e.target.closest('[data-delete]');if(!b)return;if(selected===STARTER_ID)return;if(!confirm('Удалить фразу? Подтверждение освоения урока будет сброшено.'))return;data.pairs[selected].splice(Number(b.dataset.delete),1);delete data.mastery[selected];save();renderTexts();renderExerciseStatus()});
$('#copy-text').addEventListener('click',()=>{const s=currentPairs().map(p=>p.pl).join('\n');if(!s)return alert('Фразы ещё не добавлены');navigator.clipboard?.writeText(s).then(()=>alert('Тексты скопированы')).catch(()=>alert('Копирование недоступно: открой сайт по HTTPS'))});
function renderExerciseStatus(){const n=currentPairs().length,st=data.mastery[selected]||{};$('#mastery-badge').textContent=st.complete?'✓ Урок пройден':(st.streak||0)+'/2 безошибочных раундов';if(!active)$('#exercise').innerHTML=n?'<h3>Готов к практике?</h3><p>Фраз для тренировки: '+n+'. Каждый раунд проверяет работу с польскими фразами. Если есть перевод — также проверяется его понимание.</p>':'<h3>Здесь появятся упражнения</h3><p>Для этого видео пока не удалось получить две фразы из польских субтитров. Можно добавить их вручную.</p>';$('#start-round').disabled=n<2}
function shuffled(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function begin(){const p=currentPairs();if(p.length<2)return alert('Нужно минимум две фразы');q=shuffled(p.flatMap(pair=>pair.ru?[{type:'choice',pair},{type:'write',pair}]:[{type:'copy',pair},{type:'gap',pair}]));index=0;correct=0;answered=false;active=true;renderQuestion()}
function gapFor(x){const w=x.pl.split(/\s+/);return Math.max(1,Math.floor(w.length/2))}
function expected(x){return x.type==='choice'?x.pair.ru:x.type==='gap'?x.pair.pl.split(/\s+/)[gapFor(x.pair)]:x.pair.pl}
function renderModes(){$$('[data-mode]').forEach(b=>{const on=b.dataset.mode===mode;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))})}
function tileType(x){return x.type!=='choice'&&(mode==='tiles'||mode==='mixed'&&x.useTiles!==false)}
function buildBank(x){const tokens=expected(x).split(/\s+/);const target=tokens.map((word,i)=>({id:i,word}));if(x.type==='gap'){const all=currentPairs().flatMap(p=>p.pl.split(/\s+/)).filter(w=>normalize(w)!==normalize(tokens[0]));const distractors=[...new Set(all)].slice(0,5);bank=shuffled([...target,...distractors.slice(0,3).map((word,i)=>({id:100+i,word}))])}else bank=shuffled(target);assembly=[]}
function bankHTML(){return '<div class="tile-target" id="tile-target" aria-label="Собранный ответ">'+(assembly.length?assembly.map(t=>'<button type="button" class="word-tile chosen" data-remove-tile="'+t.id+'" draggable="true" data-drag-tile="'+t.id+'">'+esc(t.word)+' ×</button>').join(''):'<span class="drop-hint">Нажимай на слова или перетащи их сюда</span>')+'</div><div class="tile-bank" id="tile-bank" aria-label="Слова для выбора">'+bank.map(t=>'<button type="button" class="word-tile" draggable="true" data-add-tile="'+t.id+'" data-drag-tile="'+t.id+'">'+esc(t.word)+'</button>').join('')+'</div><div class="tile-actions"><button class="lab-secondary" type="button" id="tile-clear">Очистить</button><button class="lab-primary" type="button" id="tile-submit" '+(!assembly.length?'disabled':'')+'>Проверить ответ</button></div>'}
function renderTiles(){const el=$('#tile-area');if(el)el.innerHTML=bankHTML()}
function renderQuestion(){const x=q[index],p=currentPairs();if(!x){finish();return}answered=false;let markup='<div class="lab-pill">ВОПРОС '+(index+1)+' ИЗ '+q.length+'</div>';
if(x.type==='choice'){const pool=shuffled(p.filter(y=>y.ru&&normalize(y.ru)!==normalize(x.pair.ru))).slice(0,3);if(!pool.length){x.type='write';return renderQuestion()}const options=shuffled([x.pair,...pool]);markup+='<h3 lang="pl">Что означает: «'+esc(x.pair.pl)+'»?</h3>'+options.map(o=>'<button class="option" data-choice="'+esc(o.ru)+'">'+esc(o.ru)+'</button>').join('')}
else{
let prompt=x.pair.ru,info='';
if(x.type==='copy'){prompt='Составь предложение на польском';info='Восстанови исходный порядок слов.'}
if(x.type==='gap'){const words=x.pair.pl.split(/\s+/),n=gapFor(x.pair);prompt='Восстанови пропущенное слово: '+words.map((w,i)=>i===n?'_____':w).join(' ');info='Выбери пропущенное слово.'}
markup+='<h3>'+esc(x.type==='write'?'Напиши по-польски: «'+prompt+'»':prompt)+'</h3>';
if(x.type==='copy')markup+='<p class="lab-muted">Расставь слова в правильном порядке.</p>';
if(mode==='mixed')markup+='<button type="button" class="lab-secondary mode-inline" id="toggle-question-mode">'+(tileType(x)?'⌨ Ввести текст':'✥ Выбрать слова')+'</button>';
if(tileType(x)){buildBank(x);markup+='<div id="tile-area">'+bankHTML()+'</div>'}else{markup+='<form id="write-form"><input id="write-answer" autocomplete="off" aria-label="Ответ на польском" required><button class="lab-primary">Проверить</button></form>'}
markup+='<p class="lab-muted">'+esc(info||'Варианты можно выбирать без клавиатуры.')+'</p>'}
$('#exercise').innerHTML=markup;renderModes();$('#start-round').textContent='Раунд идёт…';$('#start-round').disabled=true}
function tileAdd(id){if(answered)return;const i=bank.findIndex(t=>t.id===id);if(i<0)return;assembly.push(bank.splice(i,1)[0]);renderTiles()}
function tileRemove(id){if(answered)return;const i=assembly.findIndex(t=>t.id===id);if(i<0)return;bank.push(assembly.splice(i,1)[0]);renderTiles()}
function reorder(id,before){const i=assembly.findIndex(t=>t.id===id);if(i<0)return;const [item]=assembly.splice(i,1),j=assembly.findIndex(t=>t.id===before);assembly.splice(j<0?assembly.length:j,0,item);renderTiles()}
$('#exercise').addEventListener('dragstart',e=>{const t=e.target.closest('[data-drag-tile]');if(t)dragId=Number(t.dataset.dragTile)});$('#exercise').addEventListener('dragover',e=>{if(e.target.closest('#tile-target, #tile-bank'))e.preventDefault()});$('#exercise').addEventListener('drop',e=>{const target=e.target.closest('#tile-target, #tile-bank');if(!target||dragId===null)return;e.preventDefault();if(target.id==='tile-bank')tileRemove(dragId);else if(assembly.some(t=>t.id===dragId)){const at=e.target.closest('[data-remove-tile]');reorder(dragId,at?Number(at.dataset.removeTile):-1)}else tileAdd(dragId);dragId=null});
function useMode(next){mode=next;try{localStorage.setItem('pv-input-mode',mode)}catch{}renderModes();if(active&&!answered)renderQuestion()}
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>useMode(b.dataset.mode)));
function answer(given){if(answered||!active)return;answered=true;const x=q[index],answer=expected(x),ok=normalize(given)===normalize(answer);if(ok)correct++;data.events.push({at:Date.now(),videoId:selected,correct:ok});if(data.events.length>20000)data.events=data.events.slice(-20000);save();$('#exercise').insertAdjacentHTML('beforeend','<p class="feedback '+(ok?'right':'wrong')+'">'+(ok?'✓ Верно!':'✕ Правильный ответ: '+esc(answer))+'</p><button class="lab-primary" id="next-question">'+(index+1===q.length?'Завершить раунд':'Следующий вопрос →')+'</button>');$('#exercise .option, #exercise .word-tile, #exercise #tile-submit').forEach(b=>b.disabled=true);$('#write-answer')&&($('#write-answer').disabled=true)}
$('#exercise').addEventListener('click',e=>{const add=e.target.closest('[data-add-tile]'),remove=e.target.closest('[data-remove-tile]');if(add){tileAdd(Number(add.dataset.addTile));return}if(remove){tileRemove(Number(remove.dataset.removeTile));return}if(e.target.closest('#tile-clear')){bank=shuffled([...bank,...assembly]);assembly=[];renderTiles();return}if(e.target.closest('#tile-submit')){if(assembly.length===(q[index].type==='gap'?1:expected(q[index]).split(/\s+/).length))answer(assembly.map(t=>t.word).join(' '));else alert('Собери полный ответ');return}if(e.target.closest('#toggle-question-mode')){q[index].useTiles=!tileType(q[index]);renderQuestion();return}const o=e.target.closest('[data-choice]');if(o)answer(o.dataset.choice);if(e.target.closest('#next-question')){index++;renderQuestion()}});
$('#exercise').addEventListener('submit',e=>{if(e.target.id!=='write-form')return;e.preventDefault();answer($('#write-answer').value)});
function finish(){active=false;const ok=correct===q.length,old=data.mastery[selected]||{streak:0,complete:false};old.streak=ok?(old.streak||0)+1:0;old.complete=old.streak>=2;old.lastAt=Date.now();old.rounds=(old.rounds||0)+1;data.mastery[selected]=old;save();$('#exercise').innerHTML='<h3>'+(old.complete?'🏆 Урок действительно усвоен!':ok?'Идеально! Остался ещё один безошибочный раунд.':'Раунд завершён — закрепи ошибки и попробуй снова.')+'</h3><p>Правильных ответов: '+correct+' из '+q.length+'. Идеальных раундов подряд: '+old.streak+'/2.</p>';$('#start-round').textContent='Повторить раунд';$('#start-round').disabled=false;renderExerciseStatus();$('#exercise').innerHTML='<h3>'+(old.complete?'🏆 Урок пройден!':ok?'Без ошибок! Повтори ещё раз.':'Попробуй ещё раз')+'</h3><p>'+correct+' из '+q.length+' · идеальных раундов подряд: '+old.streak+'/2</p>'}
$('#start-round').addEventListener('click',begin);$('#reset-round').addEventListener('click',()=>{active=false;q=[];index=0;$('#start-round').textContent='Начать раунд';renderExerciseStatus()});
function renderAnalytics(){const e=data.events,completed=Object.values(data.mastery).filter(x=>x.complete).length;$('#stat-done').textContent=completed;$('#stat-answers').textContent=e.length;$('#stat-accuracy').textContent=e.length?Math.round(e.filter(x=>x.correct).length/e.length*100)+'%':'—';$('#stat-days').textContent=new Set(e.map(x=>day(x.at))).size;const points=Array.from({length:14},(_,i)=>{const t=Date.now()-(13-i)*86400000;return {label:day(t),n:e.filter(x=>day(x.at)===day(t)).length}}),max=Math.max(1,...points.map(x=>x.n));$('#activity-chart').innerHTML=points.map(x=>'<div class="bar-wrap" title="'+x.label+': '+x.n+' ответов"><span>'+x.n+'</span><div class="bar" style="height:'+Math.max(2,x.n/max*140)+'px"></div><small>'+x.label.slice(5)+'</small></div>').join('');const rows=Object.entries(data.mastery).map(([id,s])=>({name:videos.find(x=>x.id===id)?.title||id,s}));$('#progress-list').innerHTML=rows.length?rows.map(x=>'<div class="progress-item">'+esc(x.name)+'<span>'+(x.s.complete?'✓ Пройдено':(x.s.streak||0)+'/2 раунда')+'</span></div>').join(''):'<p class="lab-muted">Пока нет завершённых раундов.</p>'}
function renderPlan(){const g=data.goals||defaultData().goals;$('#goal-minutes').value=g.minutes||20;$('#goal-lessons').value=g.lessons||3;$('#goal-title').value=g.title||'';const week=new Date();week.setHours(0,0,0,0);week.setDate(week.getDate()-(week.getDay()+6)%7);const thisWeek=Object.values(data.mastery).filter(x=>x.complete&&x.lastAt>=week.getTime()).length;$('#goal-progress').textContent='На этой неделе: '+thisWeek+' / '+(g.lessons||3)+' пройденных уроков. Учёт минут пока не ведётся автоматически: дневная цель — ориентир, а не измеренное время.';$('#task-list').innerHTML=data.tasks.map((t,i)=>'<div class="task-list-item"><input type="checkbox" data-task="'+i+'" '+(t.done?'checked':'')+'><label style="'+(t.done?'text-decoration:line-through;color:#a0aaa0':'')+'">'+esc(t.name)+'</label><button data-task-del="'+i+'" aria-label="Удалить задачу">✕</button></div>').join('')||'<p class="lab-muted">Добавь первую задачу.</p>'}
$('#save-goals').addEventListener('click',()=>{data.goals={minutes:Math.max(5,Math.min(480,Number($('#goal-minutes').value)||20)),lessons:Math.max(1,Math.min(50,Number($('#goal-lessons').value)||3)),title:$('#goal-title').value.trim().slice(0,120)};save();renderPlan()});
$('#task-form').addEventListener('submit',e=>{e.preventDefault();const n=$('#task-input').value.trim();if(!n)return;data.tasks.push({name:n,done:false});$('#task-input').value='';save();renderPlan()});
$('#task-list').addEventListener('change',e=>{const i=e.target.dataset.task;if(i===undefined)return;data.tasks[Number(i)].done=e.target.checked;save();renderPlan()});
$('#task-list').addEventListener('click',e=>{const i=e.target.dataset.taskDel;if(i===undefined)return;data.tasks.splice(Number(i),1);save();renderPlan()});
$('#export').addEventListener('click',()=>{const b=new Blob([JSON.stringify({format:'pv-learning-v1',data},null,2)],{type:'application/json'}),url=URL.createObjectURL(b),a=document.createElement('a');a.href=url;a.download='polski-progress-'+day(Date.now())+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)});
$('#import').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2e6)throw Error('Файл больше 2 МБ');const v=JSON.parse(await f.text());if(v.format!=='pv-learning-v1'||!v.data||typeof v.data.pairs!=='object'||!Array.isArray(v.data.events)||!Array.isArray(v.data.tasks))throw Error('Неподходящий файл');if(!confirm('Заменить текущий локальный прогресс данными из файла?'))return;data=v.data;save();location.reload()}catch(err){alert('Импорт не выполнен: '+err.message)}});
async function init(){try{const r=await fetch('data/videos.json?ts='+Math.floor(Date.now()/300000),{cache:'no-cache'});if(!r.ok)throw Error('Каталог недоступен');const raw=await r.json();videos=(raw.videos||[]).filter(x=>idsafe(x.id));videos.unshift({id:STARTER_ID,title:'★ Стартовый тренажёр — 15 базовых фраз'});selected=STARTER_ID;try{const pr=await fetch('data/phrases.json?ts='+Math.floor(Date.now()/300000),{cache:'no-cache'});if(pr.ok){const phraseData=await pr.json();autoPhrases=phraseData.byVideo||{}}}catch{}populate()}catch(err){$('#video-details').textContent='Не удалось загрузить список видео: '+err.message;renderExerciseStatus();renderTexts()}renderModes();setTab(['practice','texts','analytics','plan'].includes(location.hash.slice(1))?location.hash.slice(1):'practice')}
init();
})();